[package]
name = "rb-gw"
version = "0.1.0"
edition = "2018"

[lib]
name = "rb_gw"
path = "src/lib.rs"

[[bin]]
name = "rb-gw"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rb = { path = "../common" }
