# I just use this compose file to easily start up test databases
version: '3'

services:
  db-gw:
    image: 'postgres:14-alpine'
    restart: 'always'

    environment:
      - 'POSTGRES_USER=rb'
      - 'POSTGRES_PASSWORD=rb'
    ports:
      - '5432:5432'
    # volumes:
    #   - 'db-data:/var/lib/postgresql/data'
  db-blog:
    image: 'postgres:14-alpine'
    restart: 'always'

    environment:
      - 'POSTGRES_USER=rb'
      - 'POSTGRES_PASSWORD=rb'
    ports:
      - '5433:5432'

# volumes:
#   db-data:
