[debug]
port = 8000
keep_alive = 5
read_timeout = 5
write_timeout = 5
log_level = "normal"
limits = { forms = 32768 }

[debug.databases]
postgres_rb = { url = "postgres://rb:rb@localhost:5432/rb" }

[release.databases]
postgres_rb = { url = "postgres://rb:rb@db:5432/rb" }
