[package]
name = "blog"
version = "0.1.0"
edition = "2018"

[lib]
name = "rb_blog"
path = "src/lib.rs"

[[bin]]
name = "rb-blog"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
